name: barbatos
base: core24
version: 'git'
summary: Barbatos MCP Debugger
description: |
  Barbatos is an interactive debugger for Android and iOS,
  now focused on the Model Context Protocol (MCP).

grade: stable
confinement: classic

parts:
  barbatos:
    plugin: dump
    source: dist/
    organize:
      barbatos: bin/barbatos

apps:
  barbatos:
    command: bin/barbatos
